In [1]:
# Import Libraries

import pandas as pd
import numpy as np

In [2]:
# Load Both Datasets

df1 = pd.read_csv("loan_prediction.csv")

df2 = pd.read_csv("loan_status.csv")

print(df1.head())

print(df2.head())

    Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN     

In [3]:
# Combine Both Datasets

df = pd.concat([df1, df2], axis=1)

print(df.head())

    Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001015   Male     Yes           0      Graduate            No   
1  LP001022   Male     Yes           1      Graduate            No   
2  LP001031   Male     Yes           2      Graduate            No   
3  LP001035   Male     Yes           2      Graduate            No   
4  LP001051   Male      No           0  Not Graduate            No   

  ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term  ...  \
0          5720.0               0.0      110.0            360.0  ...   
1          3076.0            1500.0      126.0            360.0  ...   
2          5000.0            1800.0      208.0            360.0  ...   
3          2340.0            2546.0      100.0            360.0  ...   
4          3276.0               0.0       78.0            360.0  ...   

   Dependents     Education Self_Employed ApplicantIncome CoapplicantIncome  \
0           0      Graduate            No            5849          

In [4]:
# Check Columns

print(df.columns)


Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_ID',
       'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')


In [5]:
# Check Null Values

print(df.isnull().sum())

Loan_ID              247
Gender               258
Married              247
Dependents           257
Education            247
Self_Employed        270
ApplicantIncome      247
CoapplicantIncome    247
LoanAmount           252
Loan_Amount_Term     253
Credit_History       276
Property_Area        247
Loan_ID                0
Gender                13
Married                3
Dependents            15
Education              0
Self_Employed         32
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            22
Loan_Amount_Term      14
Credit_History        50
Property_Area          0
Loan_Status            0
dtype: int64


In [6]:
# Fill Null Values

df.fillna(df.mode().iloc[0], inplace=True)

print(df.isnull().sum())

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64


In [9]:
print(df.columns)

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_ID',
       'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')


In [10]:
# Load datasets

df1 = pd.read_csv("loan_prediction.csv")

df2 = pd.read_csv("loan_status.csv")

In [11]:
df1['Loan_Status'] = df2['Loan_Status']

df = df1

print(df.columns)

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')


In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

columns = [
    'Gender',
    'Married',
    'Education',
    'Self_Employed',
    'Property_Area',
    'Loan_Status'
]

for col in columns:
    df[col] = encoder.fit_transform(df[col])

print(df.head())

    Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0  LP001015       1        1          0          0              0   
1  LP001022       1        1          1          0              0   
2  LP001031       1        1          2          0              0   
3  LP001035       1        1          2          0              0   
4  LP001051       1        0          0          1              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              2            0  
2             

In [13]:
# Check Null Values

print(df.isnull().sum())

Loan_ID               0
Gender                0
Married               0
Dependents           10
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
Loan_Status           0
dtype: int64


In [14]:
# Fill Null Values

df.fillna(df.mode().iloc[0], inplace=True)

print(df.isnull().sum())

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64


In [15]:
# Separate Independent and Dependent Variables

x = df.drop(['Loan_ID', 'Loan_Status'], axis=1)

y = df['Loan_Status']

print(x.head())

print(y.head())

   Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1          0          0              0             5720   
1       1        1          1          0              0             3076   
2       1        1          2          0              0             5000   
3       1        1          2          0              0             2340   
4       1        0          0          1              0             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       110.0             360.0             1.0   
1               1500       126.0             360.0             1.0   
2               1800       208.0             360.0             1.0   
3               2546       100.0             360.0             1.0   
4                  0        78.0             360.0             1.0   

   Property_Area  
0              2  
1              2  
2              2  
3              2  
4              2  
0    1
1

In [16]:
# Convert Dependents Column

x['Dependents'] = x['Dependents'].replace('3+', 3)

x['Dependents'] = x['Dependents'].astype(int)

In [17]:
# Handle Outliers

import numpy as np

numeric_columns = x.select_dtypes(include=np.number).columns

for col in numeric_columns:

    Q1 = x[col].quantile(0.25)
    Q3 = x[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    x = x[(x[col] >= lower) & (x[col] <= upper)]

# Adjust y values

y = y[x.index]

print(x.shape)

print(y.shape)

(119, 11)
(119,)


In [19]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)

print(x_scaled)

[[ 0.          0.64549722 -0.698212   ...  0.          0.
   1.0218317 ]
 [ 0.          0.64549722  0.36700887 ...  0.          0.
   1.0218317 ]
 [ 0.          0.64549722  1.43222975 ...  0.          0.
   1.0218317 ]
 ...
 [ 0.          0.64549722 -0.698212   ...  0.          0.
   1.0218317 ]
 [ 0.         -1.54919334 -0.698212   ...  0.          0.
  -0.21896394]
 [ 0.          0.64549722 -0.698212   ...  0.          0.
  -1.45975958]]


In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data:", len(x_train))
print("Testing Data:", len(x_test))

Training Data: 95
Testing Data: 24


In [21]:
# Create Logistic Regression Model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=5000)

model.fit(x_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully


In [22]:
# Predict Output

y_pred = model.predict(x_test)

print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [23]:
# Compare Actual and Predicted Values

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

print(comparison)

    Actual  Predicted
0        1          1
1        1          1
2        1          1
3        1          1
4        0          1
5        1          1
6        0          1
7        1          1
8        0          1
9        1          1
10       1          1
11       1          1
12       0          1
13       1          1
14       1          1
15       1          1
16       0          1
17       0          1
18       1          1
19       1          1
20       1          1
21       0          1
22       0          1
23       1          1


In [24]:
# Accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.6666666666666666


In [25]:
# Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 0  8]
 [ 0 16]]


In [26]:
# Precision, Recall, F1 Score

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

print("Precision:", precision)

print("Recall:", recall)

print("F1 Score:", f1)

Precision: 0.6666666666666666
Recall: 1.0
F1 Score: 0.8


In [27]:
# Classification Report

from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.67      1.00      0.80        16

    accuracy                           0.67        24
   macro avg       0.33      0.50      0.40        24
weighted avg       0.44      0.67      0.53        24



c:\Users\sirir\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\sirir\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\sirir\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [28]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(x_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully


In [29]:
y_pred = model.predict(x_test)

print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]


In [40]:
y_pred = model.predict(x_test)

In [41]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.5
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.61      0.73      0.67        15

    accuracy                           0.50        22
   macro avg       0.31      0.37      0.33        22
weighted avg       0.42      0.50      0.45        22



In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=500,
    max_depth=20,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=42
)

model.fit(x_train, y_train)

,n_estimators,500
,criterion,'gini'
,max_depth,20
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [43]:
y_pred = model.predict(x_test)

In [45]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

model.fit(x_train, y_train)

,loss,'log_loss'
,learning_rate,0.05
,n_estimators,200
,subsample,1.0
,criterion,'friedman_mse'
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_depth,5
,min_impurity_decrease,0.0
,init,None


In [46]:
y_pred = model.predict(x_test)


In [47]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.45454545454545453
              precision    recall  f1-score   support

           0       0.14      0.14      0.14         7
           1       0.60      0.60      0.60        15

    accuracy                           0.45        22
   macro avg       0.37      0.37      0.37        22
weighted avg       0.45      0.45      0.45        22



In [48]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=1000,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    bootstrap=True,
    class_weight='balanced',
    random_state=42
)

model.fit(x_train, y_train)

,n_estimators,1000
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [49]:
y_pred = model.predict(x_test)

In [50]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

Accuracy: 0.5454545454545454
              precision    recall  f1-score   support

           0       0.20      0.14      0.17         7
           1       0.65      0.73      0.69        15

    accuracy                           0.55        22
   macro avg       0.42      0.44      0.43        22
weighted avg       0.50      0.55      0.52        22



In [51]:
x_scaled


array([[ 0.        ,  0.67330033, -0.66089976, ...,  0.        ,
         0.        ,  1.01996404],
       [ 0.        ,  0.67330033,  0.67313865, ...,  0.        ,
         0.        ,  1.01996404],
       [ 0.        ,  0.67330033,  2.00717706, ...,  0.        ,
         0.        ,  1.01996404],
       ...,
       [ 0.        ,  0.67330033, -0.66089976, ...,  0.        ,
         0.        ,  1.01996404],
       [ 0.        , -1.48522131, -0.66089976, ...,  0.        ,
         0.        , -0.20175113],
       [ 0.        ,  0.67330033, -0.66089976, ...,  0.        ,
         0.        , -1.42346629]], shape=(109, 11))

In [52]:
x


,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,1,0,0,0,5720,0,110.0,360.0,1.0,2
1,1,1,1,0,0,3076,1500,126.0,360.0,1.0,2
2,1,1,2,0,0,5000,1800,208.0,360.0,1.0,2
3,1,1,2,0,0,2340,2546,100.0,360.0,1.0,2
15,1,0,1,0,0,5667,0,131.0,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...
359,1,0,0,0,0,4000,2667,152.0,360.0,1.0,1
361,1,1,1,0,0,2269,2167,99.0,360.0,1.0,1
363,1,1,0,0,0,4158,709,115.0,360.0,1.0,2
364,1,0,0,0,0,3250,1993,126.0,360.0,1.0,1


In [60]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=1000,
    criterion='entropy',
    max_depth=20,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=100
)

model.fit(x_train, y_train)

,n_estimators,1000
,criterion,'entropy'
,max_depth,20
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [61]:
y_pred = model.predict(x_test)


In [62]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.6363636363636364
              precision    recall  f1-score   support

           0       0.33      0.14      0.20         7
           1       0.68      0.87      0.76        15

    accuracy                           0.64        22
   macro avg       0.51      0.50      0.48        22
weighted avg       0.57      0.64      0.59        22

